// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWeather.Data;

#nullable disable

namespace MyWeather.Migrations
{
    [DbContext(typeof(CitiesDbContext))]
    partial class CitiesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("MyWeather.Models.Cities", b =>
                {
                    b.Property<float>("Id")
                        .HasColumnType("REAL");

                    b.Property<int>("CoordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoordId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("MyWeather.Models.Coord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("lat")
                        .HasColumnType("REAL");

                    b.Property<float>("lon")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Coord");
                });

            modelBuilder.Entity("MyWeather.Models.Cities", b =>
                {
                    b.HasOne("MyWeather.Models.Coord", "Coord")
                        .WithMany()
                        .HasForeignKey("CoordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coord");
                });
#pragma warning restore 612, 618
        }
    }
}
